backup_add_ssd script
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>

diff --git a/backup_ssd b/backup_ssd
--- a/backup_ssd
+++ b/backup_ssd
@@ -3,9 +3,12 @@
 # backup_ssd: Backup workspace to local ssd
 
 
+# Deprecated in favor of backup_all_ssd
+
+
 DISK_NAME=backup
 
-read -n 1 -p "This will copy files from local workspace into SSD disk named $DISK_NAME, are you sure you want to continue? (y/N) : " p
+read -n 1 -r -p "This will copy files from local workspace into SSD disk named $DISK_NAME, are you sure you want to continue? (y/N) : " p
 echo
 
 if [ "$p" != "y" ];then
@@ -15,9 +18,9 @@ fi
 
 # First find where the SSD is mounted
 
-mount=$(lsblk | grep $DISK_NAME | awk '{print $7}')
-[ -z $mount ] && echo "Disk not found" && exit 1
-echo $mount
+mount=$(lsblk | grep "$DISK_NAME" | awk '{print $7}')
+[ -z "$mount" ] && echo "Disk not found" && exit 1
+echo "$mount"
 
 # ~/workspace/scripts/prepare_backup.sh
 
@@ -25,9 +28,9 @@ echo $mount
 echo "---------------backing up to ssd-----------------"
 
 # Sync the whole workspace
-rsync -avhP ~/workspace $mount/backup --delete
+rsync -avhP "$HOME/workspace" "$mount/backup" --delete
 # Sync the private stuff
-rsync -avhP ~/private $mount/backup --delete
+rsync -avhP "$HOME/private" "$mount/backup" --delete
 # rclone sync ~/workspace $mount/backup/workspace -P -v --copy-links
 
 echo "---------------backed up to ssd-----------------"
