add bash set to makescript
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>

diff --git a/makescript b/makescript
--- a/makescript
+++ b/makescript
@@ -14,6 +14,7 @@ if [ ! -f "$FILE" ]; then
   read -r -p "The script $1 doesn't exist. Create? y/N : " c
   if [ "$c" = "y" ]; then
     echo "#!/usr/bin/env bash" > "$FILE"
+    echo "set -euo pipefail" >> "$FILE"
     echo "" >> "$FILE"
     echo "# $1:" >> "$FILE"
     chmod +x "$FILE"
